version: "3.9"
services:
 mssql:
  container_name: dal-performance-mssql-server
  image: "mcr.microsoft.com/mssql/server"
  ports: 
   - "1433:1433"
  environment:
   SA_PASSWORD: "complexPwd1234"
   ACCEPT_EULA: "Y"
  restart: always
