version: "3.9"
services:
 mssql:
  container_name: dapper-mssql-server
  image: "mcr.microsoft.com/mssql/server"
  ports: 
   - "1433:1433"
  environment:
   SA_PASSWORD: "dapper-secret"
   ACCEPT_EULA: "Y"
  restart: always
